python HGT.py --edge=0 --seed=12 --epochs=35 --split random
python HGT.py --edge=0 --seed=22 --epochs=35 --split random
python HGT.py --edge=0 --seed=32 --epochs=35 --split random
python HGT.py --edge=0 --seed=42 --epochs=35 --split random
python HGT.py --edge=0 --seed=52 --epochs=35 --split random
python HGT.py --edge=1 --seed=12 --epochs=35 --split random
python HGT.py --edge=1 --seed=22 --epochs=35 --split random
python HGT.py --edge=1 --seed=32 --epochs=35 --split random
python HGT.py --edge=1 --seed=42 --epochs=35 --split random
python HGT.py --edge=1 --seed=52 --epochs=35 --split random

python HGT.py --edge=0 --seed=1 --epochs=10 --split complex_disease
python HGT.py --edge=0 --seed=2 --epochs=10 --split complex_disease
python HGT.py --edge=0 --seed=3 --epochs=10 --split complex_disease
python HGT.py --edge=0 --seed=4 --epochs=10 --split complex_disease
python HGT.py --edge=0 --seed=5 --epochs=10 --split complex_disease
python HGT.py --edge=1 --seed=1 --epochs=10 --split complex_disease
python HGT.py --edge=1 --seed=2 --epochs=10 --split complex_disease
python HGT.py --edge=1 --seed=3 --epochs=10 --split complex_disease
python HGT.py --edge=1 --seed=4 --epochs=10 --split complex_disease
python HGT.py --edge=1 --seed=5 --epochs=10 --split complex_disease

python HGT.py --edge=0 --seed=1 --epochs=10 --split cell_proliferation
python HGT.py --edge=0 --seed=2 --epochs=10 --split cell_proliferation
python HGT.py --edge=0 --seed=3 --epochs=10 --split cell_proliferation
python HGT.py --edge=0 --seed=4 --epochs=10 --split cell_proliferation
python HGT.py --edge=0 --seed=5 --epochs=10 --split cell_proliferation
python HGT.py --edge=1 --seed=1 --epochs=10 --split cell_proliferation
python HGT.py --edge=1 --seed=2 --epochs=10 --split cell_proliferation
python HGT.py --edge=1 --seed=3 --epochs=10 --split cell_proliferation
python HGT.py --edge=1 --seed=4 --epochs=10 --split cell_proliferation
python HGT.py --edge=1 --seed=5 --epochs=10 --split cell_proliferation

python HGT.py --edge=0 --seed=1 --epochs=10 --split mental_health
python HGT.py --edge=0 --seed=2 --epochs=10 --split mental_health
python HGT.py --edge=0 --seed=3 --epochs=10 --split mental_health
python HGT.py --edge=0 --seed=4 --epochs=10 --split mental_health
python HGT.py --edge=0 --seed=5 --epochs=10 --split mental_health
python HGT.py --edge=1 --seed=1 --epochs=10 --split mental_health
python HGT.py --edge=1 --seed=2 --epochs=10 --split mental_health
python HGT.py --edge=1 --seed=3 --epochs=10 --split mental_health
python HGT.py --edge=1 --seed=4 --epochs=10 --split mental_health
python HGT.py --edge=1 --seed=5 --epochs=10 --split mental_health

python HGT.py --edge=0 --seed=1 --epochs=10 --split cardiovascular
python HGT.py --edge=0 --seed=2 --epochs=10 --split cardiovascular
python HGT.py --edge=0 --seed=3 --epochs=10 --split cardiovascular
python HGT.py --edge=0 --seed=4 --epochs=10 --split cardiovascular
python HGT.py --edge=0 --seed=5 --epochs=10 --split cardiovascular
python HGT.py --edge=1 --seed=1 --epochs=10 --split cardiovascular
python HGT.py --edge=1 --seed=2 --epochs=10 --split cardiovascular
python HGT.py --edge=1 --seed=3 --epochs=10 --split cardiovascular
python HGT.py --edge=1 --seed=4 --epochs=10 --split cardiovascular
python HGT.py --edge=1 --seed=5 --epochs=10 --split cardiovascular

python HGT.py --edge=0 --seed=1 --epochs=10 --split anemia
python HGT.py --edge=0 --seed=2 --epochs=10 --split anemia
python HGT.py --edge=0 --seed=3 --epochs=10 --split anemia
python HGT.py --edge=0 --seed=4 --epochs=10 --split anemia
python HGT.py --edge=0 --seed=5 --epochs=10 --split anemia
python HGT.py --edge=1 --seed=1 --epochs=10 --split anemia
python HGT.py --edge=1 --seed=2 --epochs=10 --split anemia
python HGT.py --edge=1 --seed=3 --epochs=10 --split anemia
python HGT.py --edge=1 --seed=4 --epochs=10 --split anemia
python HGT.py --edge=1 --seed=5 --epochs=10 --split anemia

python HGT.py --edge=0 --seed=1 --epochs=10 --split adrenal_gland
python HGT.py --edge=0 --seed=2 --epochs=10 --split adrenal_gland
python HGT.py --edge=0 --seed=3 --epochs=10 --split adrenal_gland
python HGT.py --edge=0 --seed=4 --epochs=10 --split adrenal_gland
python HGT.py --edge=0 --seed=5 --epochs=10 --split adrenal_gland
python HGT.py --edge=1 --seed=1 --epochs=10 --split adrenal_gland
python HGT.py --edge=1 --seed=2 --epochs=10 --split adrenal_gland
python HGT.py --edge=1 --seed=3 --epochs=10 --split adrenal_gland
python HGT.py --edge=1 --seed=4 --epochs=10 --split adrenal_gland
python HGT.py --edge=1 --seed=5 --epochs=10 --split adrenal_gland

python HGT.py --edge=0 --seed=1 --epochs=10 --split autoimmune
python HGT.py --edge=0 --seed=2 --epochs=10 --split autoimmune
python HGT.py --edge=0 --seed=3 --epochs=10 --split autoimmune
python HGT.py --edge=0 --seed=4 --epochs=10 --split autoimmune
python HGT.py --edge=0 --seed=5 --epochs=10 --split autoimmune
python HGT.py --edge=1 --seed=1 --epochs=10 --split autoimmune
python HGT.py --edge=1 --seed=2 --epochs=10 --split autoimmune
python HGT.py --edge=1 --seed=3 --epochs=10 --split autoimmune
python HGT.py --edge=1 --seed=4 --epochs=10 --split autoimmune
python HGT.py --edge=1 --seed=5 --epochs=10 --split autoimmune

python HGT.py --edge=0 --seed=1 --epochs=10 --split metabolic_disorder
python HGT.py --edge=0 --seed=2 --epochs=10 --split metabolic_disorder
python HGT.py --edge=0 --seed=3 --epochs=10 --split metabolic_disorder
python HGT.py --edge=0 --seed=4 --epochs=10 --split metabolic_disorder
python HGT.py --edge=0 --seed=5 --epochs=10 --split metabolic_disorder
python HGT.py --edge=1 --seed=1 --epochs=10 --split metabolic_disorder
python HGT.py --edge=1 --seed=2 --epochs=10 --split metabolic_disorder
python HGT.py --edge=1 --seed=3 --epochs=10 --split metabolic_disorder
python HGT.py --edge=1 --seed=4 --epochs=10 --split metabolic_disorder
python HGT.py --edge=1 --seed=5 --epochs=10 --split metabolic_disorder

python HGT.py --edge=0 --seed=1 --epochs=10 --split diabetes
python HGT.py --edge=0 --seed=2 --epochs=10 --split diabetes
python HGT.py --edge=0 --seed=3 --epochs=10 --split diabetes
python HGT.py --edge=0 --seed=4 --epochs=10 --split diabetes
python HGT.py --edge=0 --seed=5 --epochs=10 --split diabetes
python HGT.py --edge=1 --seed=1 --epochs=10 --split diabetes
python HGT.py --edge=1 --seed=2 --epochs=10 --split diabetes
python HGT.py --edge=1 --seed=3 --epochs=10 --split diabetes
python HGT.py --edge=1 --seed=4 --epochs=10 --split diabetes
python HGT.py --edge=1 --seed=5 --epochs=10 --split diabetes

python HGT.py --edge=0 --seed=1 --epochs=10 --split neurodigenerative
python HGT.py --edge=0 --seed=2 --epochs=10 --split neurodigenerative
python HGT.py --edge=0 --seed=3 --epochs=10 --split neurodigenerative
python HGT.py --edge=0 --seed=4 --epochs=10 --split neurodigenerative
python HGT.py --edge=0 --seed=5 --epochs=10 --split neurodigenerative
python HGT.py --edge=1 --seed=1 --epochs=10 --split neurodigenerative
python HGT.py --edge=1 --seed=2 --epochs=10 --split neurodigenerative
python HGT.py --edge=1 --seed=3 --epochs=10 --split neurodigenerative
python HGT.py --edge=1 --seed=4 --epochs=10 --split neurodigenerative
python HGT.py --edge=1 --seed=5 --epochs=10 --split neurodigenerative